apiVersion: v1
kind: Namespace
metadata:
  name: dockercoins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dockercoins
spec:
#  replicas: 3
  selector:
    matchLabels:
      app: dockercoins
      tier: worker
  template:
    metadata:
      labels:
        app: dockercoins
        tier: worker
    spec:
      containers:
      - name: worker
        image: brahimhamdi/worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
  namespace: dockercoins
spec:
#  replicas: 3
  selector:
    matchLabels:
      app: dockercoins
      tier: rng
  template:
    metadata:
      labels:
        app: dockercoins
        tier: rng
    spec:
      containers:
      - name: rng
        image: brahimhamdi/rng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
  namespace: dockercoins
spec:
#  replicas: 3
  selector:
    matchLabels:
      app: dockercoins
      tier: hasher
  template:
    metadata:
      labels:
        app: dockercoins
        tier: hasher
    spec:
      containers:
      - name: hasher
        image: brahimhamdi/hasher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: dockercoins
spec:
#  replicas: 3
  selector:
    matchLabels:
      app: dockercoins
      tier: redis
  template:
    metadata:
      labels:
        app: dockercoins
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: dockercoins
spec:
#  replicas: 3
  selector:
    matchLabels:
      app: dockercoins
      tier: webui
  template:
    metadata:
      labels:
        app: dockercoins
        tier: webui
    spec:
      containers:
      - name: webui
        image: brahimhamdi/webui
---
apiVersion: v1
kind: Service
metadata:
  name: rng
  namespace: dockercoins
spec:
  selector:
    app: dockercoins
    tier: rng
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  namespace: dockercoins
spec:
  selector:
    app: dockercoins
    tier: hasher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dockercoins
spec:
  selector:
    app: dockercoins
    tier: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: dockercoins
spec:
  selector:
    app: dockercoins
    tier: webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
