apiVersion: v1
kind: Service
metadata:
  name: frontsrv
spec:
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backsrv
spec:
  selector:
    app: back
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31002
      protocol: TCP
  type: NodePort
