---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dockercoins
  name: hasher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercoins
      tier: hasher
  template:
    metadata:
      labels:
        app: dockercoins
        tier: hasher
    spec:
      containers:
      - image: brahimhamdi/dockercoins_hasher
        name: hasher
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockercoins
  name: hasher
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dockercoins
    tier: hasher
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dockercoins
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercoins
      tier: redis
  template:
    metadata:
      labels:
        app: dockercoins
        tier: redis
    spec:
      containers:
      - image: redis
        name: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockercoins
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: dockercoins
    tier: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dockercoins
  name: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercoins
      tier: rng
  template:
    metadata:
      labels:
        app: dockercoins
        tier: rng
    spec:
      containers:
      - image: brahimhamdi/dockercoins_rng
        name: rng
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockercoins
  name: rng
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dockercoins
    tier: rng
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dockercoins
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercoins
      tier: webui
  template:
    metadata:
      labels:
        app: dockercoins
        tier: webui
    spec:
      containers:
      - image: brahimhamdi/dockercoins_webui
        name: webui
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockercoins
  name: webui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dockercoins
    tier: webui
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dockercoins
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockercoins
      tier: worker
  template:
    metadata:
      labels:
        app: dockercoins
        tier: worker
    spec:
      containers:
      - image: brahimhamdi/dockercoins_worker
        name: worker
