filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /lognginx/*access.log
    - /logdb/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.overwrite_keys: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

setup.kibana:

output.logstash:
  hosts: ["logstash:5044"]
